name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven Checkstyle
      run: mvn checkstyle:check
      continue-on-error: true

    - name: Initialise CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: java

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: CodeQL Analysis
      uses: github/codeql-action/analyze@v4


    - name: Run Unit Tests
      run: mvn test

    - name: Build Docker Image
      run: docker build -t atm-system:latest .

    - name: Run Container and Test
      run: |
        docker run -d --name atm-container atm-system
        sleep 20
        docker stop atm-container
        docker rm atm-container

    - name: Trivy image scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: atm-system:latest
        scan-type: image
        format: table

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Tag image for Docker Hub
      run: docker tag atm-system:latest ${{ secrets.DOCKERHUB_USERNAME }}/atm-system:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/atm-system:latest
      